### ISSUE TITLE
missing mib

### ISSUE THREAD

**Issue by chrisns** [mtdcr/pductl#1]
For anyone else with this issue:
```atenpdu.AtenPEError: ATEN-PE-CFG compilation error(s): Illegal character '<', 1809 characters left unparsed at this stage at MIB ATEN-PE-CFG, line 1caused by <class 'pysnmp.smi.error.MibNotFoundError'>: MIB file "ATEN-PE-CFG.py[co]" not found in search path (DirMibSource('/usr/local/lib/python3.9/site-packages/pysnmp/smi/mibs'), DirMibSource('/usr/local/lib/python3.9/site-packages/pysnmp/smi/mibs/instances'), DirMibSource('pysnmp_mibs'), DirMibSource('/root/.pysnmp/mibs'))```

```bash
curl https://mibs.thola.io/pysnmp/ATEN-PE-CFG.py > /root/.pysnmp/mibs/ATEN-PE-CFG.py
```

worked for me, there's probably a way better way to do this with python/pysnmp etc

## demo in docker for isolation:

```bash
$ docker run --rm -ti - python:3 bash
$ pip3 install aten_pdu
$ echo '{
  "format": 1,
  "pdus": {
    "pdu1": {
      "node": "192.168.0.60",
      "service": "snmp",
      "username": "administrator",
      "authkey": "AAAAAAAAAAAAAA",
      "privkey": "BBBBBBBBBBBBBB"
    }
  }
}' > /root/.pductl
$ pductl -p pdu1 list
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pysnmp/smi/builder.py", line 401, in loadModules
    self.loadModule(modName, **userCtx)
  File "/usr/local/lib/python3.9/site-packages/pysnmp/smi/builder.py", line 377, in loadModule
    raise error.MibNotFoundError(
pysnmp.smi.error.MibNotFoundError: MIB file "ATEN-PE-CFG.py[co]" not found in search path (DirMibSource('/usr/local/lib/python3.9/site-packages/pysnmp/smi/mibs'), DirMibSource('/usr/local/lib/python3.9/site-packages/pysnmp/smi/mibs/instances'), DirMibSource('pysnmp_mibs'), DirMibSource('/root/.pysnmp/mibs'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/atenpdu.py", line 70, in initialize
    mibBuilder.loadModules(self._MIB_MODULE)
  File "/usr/local/lib/python3.9/site-packages/pysnmp/smi/builder.py", line 410, in loadModules
    raise error.MibNotFoundError('%s compilation error(s): %s' % (modName, errs))
pysnmp.smi.error.MibNotFoundError: ATEN-PE-CFG compilation error(s): Illegal character '<', 1809 characters left unparsed at this stage at MIB ATEN-PE-CFG, line 1caused by <class 'pysnmp.smi.error.MibNotFoundError'>: MIB file "ATEN-PE-CFG.py[co]" not found in search path (DirMibSource('/usr/local/lib/python3.9/site-packages/pysnmp/smi/mibs'), DirMibSource('/usr/local/lib/python3.9/site-packages/pysnmp/smi/mibs/instances'), DirMibSource('pysnmp_mibs'), DirMibSource('/root/.pysnmp/mibs'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pductl", line 194, in <module>
    loop.run_until_complete(main(args))
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/bin/pductl", line 159, in main
    ctrl.initialize()
  File "/usr/local/lib/python3.9/site-packages/atenpdu.py", line 72, in initialize
    raise AtenPEError(str(exc))
atenpdu.AtenPEError: ATEN-PE-CFG compilation error(s): Illegal character '<', 1809 characters left unparsed at this stage at MIB ATEN-PE-CFG, line 1caused by <class 'pysnmp.smi.error.MibNotFoundError'>: MIB file "ATEN-PE-CFG.py[co]" not found in search path (DirMibSource('/usr/local/lib/python3.9/site-packages/pysnmp/smi/mibs'), DirMibSource('/usr/local/lib/python3.9/site-packages/pysnmp/smi/mibs/instances'), DirMibSource('pysnmp_mibs'), DirMibSource('/root/.pysnmp/mibs'))
$ mkdir -p /root/.pysnmp/mibs
$ curl -s https://mibs.thola.io/pysnmp/ATEN-PE-CFG.py > /root/.pysnmp/mibs/ATEN-PE-CFG.py
$ pductl -p pdu1 list
```

**Comment by chrisns** [comment]
.... further, looks like this domain has expired:
https://github.com/mtdcr/pductl/blob/2836f0794347faf642fdb6ad9a1108e20c24f1e8/atenpdu.py#L37

**Comment by chrisns** [comment]
https://github.com/inexio/mibs.snmplabs.com
https://github.com/inexio/pysnmp-mibs
https://mibs.thola.io/asn1/

may be able to help, either referencing, depending or something else ¯\_(ツ)_/¯

**Comment by chrisns** [comment]
Closed by #2
